apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: process-flow-platform-dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: microtema/process-flow-platform-frontend:0.1.7
          ports:
            - containerPort: 4200
          env:
            - name: OKTA_OAUTH2_ISSUER
              value: https://dev-1065782.okta.com/oauth2/default
            - name: OKTA_OAUTH2_CLIENTID
              value: 0oa3h0mq2kwRxe9hO5d6
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: process-flow-platform-dev
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: process-flow-platform-dev
spec:
  tls:
    - hosts:
        - microtema.com
      secretName: secret-tls
  rules:
    - host: microtema.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 4200
